# Generated by Django 3.1.4 on 2021-01-17 14:24

import django.core.files.storage
from django.db import migrations, models
import hospital.models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/my_sell/', location='C:\\Users\\ALPARSLAN\\Desktop\\UW\\SEMESTER_1\\Python&SQL\\Project\\hospital_app\\media/my_sell/'), upload_to=hospital.models.image_directory_path)),
            ],
        ),
    ]
