# Generated by Django 3.1.4 on 2021-01-17 14:39

import django.core.files.storage
from django.db import migrations, models
import hospital.models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='pic',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/picture/', location='C:\\Users\\ALPARSLAN\\Desktop\\UW\\SEMESTER_1\\Python&SQL\\Project\\hospital_app\\media/picture/'), upload_to=hospital.models.image_directory_path),
        ),
    ]
