# Generated by Django 3.1.4 on 2021-01-17 14:40

from django.db import migrations, models
import hospital.models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20210117_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='pic',
            field=models.ImageField(upload_to=hospital.models.image_directory_path),
        ),
    ]
