# Generated by Django 3.1.4 on 2021-01-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20210117_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
